In [2]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
a[1,6]


14

In [4]:
np.random.random_sample(a.shape)

array([[0.0528523 , 0.87491691, 0.37229209, 0.36474863, 0.9638403 ,
        0.69999722, 0.22031285],
       [0.19382189, 0.43813357, 0.95188975, 0.61385638, 0.33294124,
        0.3783691 , 0.06873589]])

In [6]:
np.random.randint(10,280,size=(5,4))
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
arr1=np.array([[1,2,3]])
r1=np.repeat(arr1,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
output=np.full((5,5),3)
z=np.full((3,3),2)
z[1][1]=1
output[1:4,1:4]=z
print(output)

[[3 3 3 3 3]
 [3 2 2 2 3]
 [3 2 1 2 3]
 [3 2 2 2 3]
 [3 3 3 3 3]]


In [47]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [61]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [62]:
a+=2
print(a)

[3 4 5 6]


In [63]:
a-=2
print(a)

[1 2 3 4]


In [65]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [67]:
a**2


array([ 1,  4,  9, 16])

In [68]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [71]:
np.random.normal(0,1,(3,3))

array([[-0.13969802, -0.53286588, -2.08914786],
       [-1.34738087,  1.90959271,  0.10790474],
       [-1.35341224,  0.45524274, -0.39980774]])

In [73]:
a

array([1, 2, 3, 4])

In [75]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [77]:
grid = np.arange(1,10,1).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
x=np.array([1,2,3])
x
# x.reshape(1,3).shape

array([1, 2, 3])

In [86]:
x[np.newaxis, :].shape

(1, 3)

In [87]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [88]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [89]:
np.concatenate((grid,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [90]:
np.concatenate((grid, grid), axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [92]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])


# vertically stack the arrays
np.vstack([grid,x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [93]:
y = np.array([[99],
            [99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Splitting functions begin

In [94]:
x = np.array([1,2,3,99,99,3,2,1])
x1, x2, x3, x4 = np.split(x, [3,4,5])
print(x1, x2, x3,x4)

[1 2 3] [99] [99] [3 2 1]


In [101]:
grid=np.arange(36).reshape(6,6)

grid

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [103]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [104]:
upper,middle, lower = np.vsplit(grid, [2,3])
print("upper: ",upper)
print("middle: ",middle)
print("lower: ",lower)

upper:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
middle:  [[12 13 14 15 16 17]]
lower:  [[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [105]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]]
[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]
 [32 33 34 35]]


In [117]:




# Split the grid into 3 equal parts along the columns (axis=1)
parts = np.split(grid, 3, axis=1)

# Print each part
for i, part in enumerate(parts):
    print(f"Part {i + 1}:\n{part}\n")


Part 1:
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]]

Part 2:
[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]
 [26 27]
 [32 33]]

Part 3:
[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]
 [34 35]]



In [126]:
x=np.array([1,2,3])
np.exp(np.log(x))

array([1., 2., 3.])

In [132]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [134]:
#This can even be used with array views. For example, we can write the results of a
#computation to every other element of a specified array:

y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

# If we had instead written y[::2] = 2 ** x, this would have resulted in the creation
# of a temporary array to hold the results of 2 ** x, followed by a second operation
# copying those values into the y array. This doesn’t make much of a difference for such
# a small computation, but for very large arrays the memory savings from careful use of
# the out argument can be significant.

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [136]:
x=np.array([1,2,3,4,5,6])
np.subtract.reduce(x)

-19

In [138]:
#If we’d like to store all the intermediate results of the computation, we can instead use
#accumulate:

print(np.add.accumulate(x))
print(np.subtract.accumulate(x))
print(np.multiply.accumulate(x))
print(np.divide.accumulate(x))
print(np.floor_divide.accumulate(x))

[ 1  3  6 10 15 21]
[  1  -1  -4  -8 -13 -19]
[  1   2   6  24 120 720]
[1.         0.5        0.16666667 0.04166667 0.00833333 0.00138889]
[1 0 0 0 0 0]


In [139]:
x = np.arange(1,6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [173]:
L = np.random.rand((1,100))
L


array([[0.95275297, 0.71220001, 0.88242239, 0.01443257, 0.78736742,
        0.26655217, 0.66796815, 0.69506116, 0.28470183, 0.79604478,
        0.68367921, 0.7482505 , 0.08462723, 0.93513017, 0.11960027,
        0.88895205, 0.23176406, 0.97644824, 0.47206786, 0.58024202,
        0.64570596, 0.18538752, 0.77616181, 0.12152914, 0.50302607,
        0.94531811, 0.58626116, 0.80094775, 0.4975061 , 0.38463991,
        0.25288992, 0.62334124, 0.87966237, 0.9477871 , 0.43024777,
        0.37449923, 0.78508828, 0.04350831, 0.23632102, 0.86140039,
        0.19682762, 0.03339687, 0.56460545, 0.50449823, 0.38532903,
        0.03682433, 0.23715741, 0.28748914, 0.7705685 , 0.99794329,
        0.71237862, 0.82089784, 0.26969708, 0.39596412, 0.26883886,
        0.9958181 , 0.29548769, 0.01066857, 0.35439149, 0.64239989,
        0.58613568, 0.11703045, 0.92095918, 0.22121229, 0.32150644,
        0.64755799, 0.74059051, 0.31237382, 0.60603438, 0.85343561,
        0.70468079, 0.74198461, 0.7342768 , 0.99

In [174]:
M = np.random.random((3,4))
print(M)

M.sum()

[[0.75061376 0.72473672 0.83166335 0.538807  ]
 [0.91794835 0.25801793 0.51264339 0.44998889]
 [0.19308787 0.95035135 0.6391687  0.1931335 ]]


6.9601607977628595

In [176]:
print(M.min(axis=0))
#or use that way
print(np.min(M,axis=0))
M

[0.19308787 0.25801793 0.51264339 0.1931335 ]
[0.19308787 0.25801793 0.51264339 0.1931335 ]


array([[0.75061376, 0.72473672, 0.83166335, 0.538807  ],
       [0.91794835, 0.25801793, 0.51264339, 0.44998889],
       [0.19308787, 0.95035135, 0.6391687 , 0.1931335 ]])

In [179]:
a=np.array([0,1,2])
M=np.ones((3,3))
a=a[:,np.newaxis]
b=np.arange(3)
M+a
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [185]:
rng = np.random.RandomState(seed=0)
x = rng.randint(10, size=(3,4))
print(x)

x<6

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [186]:
print(x)
print(x<5)
print(x[x<5])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]


In [187]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [188]:
ind = [3,7,4]
x[ind]

array([71, 86, 60])

In [189]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [191]:
X = np.arange(12).reshape((3,4))

row = np.array([0,1,2])
col = np.array([2,1,3])
X[row,col]

array([ 2,  5, 11])

In [193]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [194]:
X[2,[2,0,1]]

array([10,  8,  9])

In [195]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [196]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [197]:
mask = np.array([1, 0, 1, 0], dtype=bool)
X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [198]:
x = np.zeros(10)
x[[0, 2]] = [4, 6]
print(x)

[4. 0. 6. 0. 0. 0. 0. 0. 0. 0.]


In [199]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)


[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [200]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [201]:
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


In [202]:
x = np.array([2,1,4,3,5])
i = np.argsort(x)
print(i)

x[i]

[1 0 3 2 4]


array([1, 2, 3, 4, 5])