In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.DataFrame([[4,7,10],[6,8,2],[1,3,4],[2,10,5]])

In [4]:
df.iloc[1:4]

0   1  2
1  6   8  2
2  1   3  4
3  2  10  5

In [5]:
x = np.array([[1, 2], [3, 4], [2, 2], [9, 6]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

29
[15 14]
[ 3  7  4 15]


In [10]:
x=np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
v=np.array([4,0,2,1])

In [12]:
y = x+v
y

array([[4., 0., 2., 1.],
       [4., 0., 2., 1.],
       [4., 0., 2., 1.],
       [4., 0., 2., 1.]])

In [13]:
a=['a','b','c','d']
a[0]='j'
print(a)

['j', 'b', 'c', 'd']


In [14]:
s='hewubewbo'

print(s)

TypeError: 'str' object does not support item assignment